"""server defaults

Revision ID: 0999ba8704a6
Revises: 5f9e841b7ab8
Create Date: 2021-11-20 15:17:50.651218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0999ba8704a6'
down_revision = '5f9e841b7ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridgecharacters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridgenpcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['np_cs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridgeplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('copper_value', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridgeitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('loot')
    op.add_column('characters', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.drop_constraint('characters_game_id_fkey', 'characters', type_='foreignkey')
    op.drop_column('characters', 'game_id')
    op.add_column('games', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.add_column('images', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.add_column('images', sa.Column('user_id', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'])
    op.add_column('notes', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.add_column('np_cs', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.drop_constraint('np_cs_game_id_fkey', 'np_cs', type_='foreignkey')
    op.drop_column('np_cs', 'game_id')
    op.add_column('places', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.drop_constraint('places_game_id_fkey', 'places', type_='foreignkey')
    op.drop_column('places', 'game_id')
    op.add_column('players', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.add_column('sessions', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.add_column('users', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'removed')
    op.drop_column('sessions', 'removed')
    op.drop_column('players', 'removed')
    op.add_column('places', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('places_game_id_fkey', 'places', 'games', ['game_id'], ['id'])
    op.drop_column('places', 'removed')
    op.add_column('np_cs', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('np_cs_game_id_fkey', 'np_cs', 'games', ['game_id'], ['id'])
    op.drop_column('np_cs', 'removed')
    op.drop_column('notes', 'removed')
    op.drop_column('images', 'user_id')
    op.drop_column('images', 'removed')
    op.drop_column('games', 'removed')
    op.add_column('characters', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('characters_game_id_fkey', 'characters', 'games', ['game_id'], ['id'])
    op.drop_column('characters', 'removed')
    op.create_table('loot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('copper_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['characters.id'], name='loot_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='loot_pkey')
    )
    op.drop_table('bridgeitems')
    op.drop_table('items')
    op.drop_table('bridgeplaces')
    op.drop_table('bridgenpcs')
    op.drop_table('bridgecharacters')
    # ### end Alembic commands ###
