"""empty message

Revision ID: 10cc64216e44
Revises: b86fc8f46a8d
Create Date: 2021-08-01 17:26:09.970368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10cc64216e44'
down_revision = 'b86fc8f46a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('session_number', sa.Integer(), nullable=True))
    op.drop_column('notes', 'session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('notes', 'session_number')
    # ### end Alembic commands ###
