""" Update games

Revision ID: 1dffb7697400
Revises: 18deb2eb139b
Create Date: 2022-02-08 19:29:12.814114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dffb7697400'
down_revision = '18deb2eb139b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.add_column('games', sa.Column('finished', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.drop_column('games', 'secret')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('secret', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('games', 'finished')
    op.drop_column('games', 'removed')
    # ### end Alembic commands ###
