""" update npcs

Revision ID: 18deb2eb139b
Revises: 7462b5348a50
Create Date: 2022-02-08 19:24:03.726286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18deb2eb139b'
down_revision = '7462b5348a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('npcs', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.add_column('npcs', sa.Column('img_id', sa.Integer(), nullable=True))
    op.add_column('npcs', sa.Column('user_id', sa.Integer(), server_default=sa.text('-2'), nullable=False))
    op.drop_constraint('np_cs_game_id_fkey', 'npcs', type_='foreignkey')
    op.create_foreign_key('npcs_img_id_fkey', 'npcs', 'images', ['img_id'], ['id'])
    op.create_foreign_key('npcs_user_id_fkey', 'npcs', 'users', ['user_id'], ['id'])
    op.drop_column('npcs', 'game_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('game_id', sa.INTEGER(), server_default=sa.text('-2'), autoincrement=False, nullable=False))
    op.drop_constraint('npcs_img_id_fkey', 'npcs', type_='foreignkey')
    op.drop_constraint('npcs_user_id_fkey', 'npcs', type_='foreignkey')
    op.create_foreign_key('np_cs_game_id_fkey', 'npcs', 'games', ['game_id'], ['id'])
    op.drop_column('npcs', 'user_id')
    op.drop_column('npcs', 'img_id')
    op.drop_column('npcs', 'removed')
    # ### end Alembic commands ###
