""" drop owner_id from items

Revision ID: b4d0ccba3876
Revises: 1dffb7697400
Create Date: 2022-02-08 19:33:04.897175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d0ccba3876'
down_revision = '1dffb7697400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('loot_owner_id_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('loot_owner_id_fkey', 'items', 'characters', ['owner_id'], ['id'])
    # ### end Alembic commands ###
