"""initial migrate after refactor

Revision ID: b351a2c3942c
Revises: 
Create Date: 2022-01-15 22:47:45.220882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b351a2c3942c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('img_string', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('copper_value', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('secret_bio', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=120), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bridgeimages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('dm', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('copy', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('published', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('dm_id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dm_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('secret_name', sa.String(length=40), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('secret_bio', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('img_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridgecharacters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('dm', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridgeitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridgenpcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridgeplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('charname', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('to_dm', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('origin_character_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['origin_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('owner', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('players')
    op.drop_table('notes')
    op.drop_table('bridgeplaces')
    op.drop_table('bridgenpcs')
    op.drop_table('bridgeitems')
    op.drop_table('bridgecharacters')
    op.drop_table('npcs')
    op.drop_table('games')
    op.drop_table('characters')
    op.drop_table('bridgeimages')
    op.drop_table('users')
    op.drop_table('places')
    op.drop_table('items')
    op.drop_table('images')
    # ### end Alembic commands ###
