"""update bridgeusergames

Revision ID: bed97e30bb1d
Revises: 7961f86915f5
Create Date: 2022-02-08 20:08:05.052526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed97e30bb1d'
down_revision = '7961f86915f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridgeusergames', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.add_column('bridgeusergames', sa.Column('owner', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.alter_column('bridgeusergames', 'games_id', new_column_name='game_id')
    op.alter_column('bridgeusergames', 'users_id', new_column_name='user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bridgeusergames', 'user_id', new_column_name='users_id')
    op.alter_column('bridgeusergames', 'game_id', new_column_name='games_id')
    op.drop_column('bridgeusergames', 'owner')
    op.drop_column('bridgeusergames', 'removed')
    # ### end Alembic commands ###
