"""update sessions

Revision ID: e091f1b683f4
Revises: 9e4e29bc5b57
Create Date: 2022-02-08 19:55:27.673090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e091f1b683f4'
down_revision = '9e4e29bc5b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.alter_column('sessions', 'games_id', new_column_name='game_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'game_id', new_column_name='games_id')
    op.drop_column('sessions', 'removed')
    # ### end Alembic commands ###
