"""Update notes

Revision ID: 9e4e29bc5b57
Revises: 2d9a06f848ea
Create Date: 2022-02-08 19:42:57.515862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4e29bc5b57'
down_revision = '2d9a06f848ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.alter_column('notes', 'note', new_column_name='text')
    op.alter_column('notes', 'to_gm', new_column_name='to_dm')
    op.alter_column('notes', 'character', new_column_name='origin_character_id')
    op.alter_column('notes', 'charname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key('notes_origin_character_id_fkey', 'notes', 'characters', ['origin_character_id'], ['id'])
    op.drop_constraint('notes_character_fkey', 'notes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notes_origin_character_id_fkey', 'notes', type_='foreignkey')
    op.alter_column('notes', 'charname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('notes', 'origin_character_id', new_column_name='character')
    op.create_foreign_key('notes_character_fkey', 'notes', 'characters', ['character'], ['id'])
    op.alter_column('notes', 'to_dm', new_column_name='to_gm')
    op.alter_column('notes', 'text', new_column_name='note')
    op.drop_column('notes', 'removed')
    # ### end Alembic commands ###
