"""empty message

Revision ID: 2ff1ed968a1f
Revises: a82fde915fa5
Create Date: 2021-09-04 19:17:40.236588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ff1ed968a1f'
down_revision = 'a82fde915fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'imglink',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('games', 'imglink',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'imglink',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('characters', 'imglink',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
