"""empty message

Revision ID: 41024ba6cb8f
Revises: 71c411eb6ded
Create Date: 2021-07-26 17:20:35.885101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41024ba6cb8f'
down_revision = '71c411eb6ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
