"""changed tables to work with new images table. Also deleted unused character table rows'




Revision ID: 45750fca9568
Revises: b3b14a30d105
Create Date: 2021-09-10 14:48:36.931668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45750fca9568'
down_revision = 'b3b14a30d105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('img')
    op.drop_column('characters', 'intelligence')
    op.drop_column('characters', 'platinum')
    op.drop_column('characters', 'electrum')
    op.drop_column('characters', 'dexterity')
    op.drop_column('characters', 'copper')
    op.drop_column('characters', 'silver')
    op.drop_column('characters', 'constitution')
    op.drop_column('characters', 'wisdom')
    op.drop_column('characters', 'imglink')
    op.drop_column('characters', 'strength')
    op.drop_column('characters', 'gold')
    op.drop_column('characters', 'charisma')
    op.drop_column('characters', 'experience')
    op.add_column('games', sa.Column('img_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'images', ['img_id'], ['id'])
    op.drop_column('games', 'imglink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('imglink', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'img_id')
    op.add_column('characters', sa.Column('experience', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('charisma', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('gold', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('strength', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('imglink', mysql.TEXT(), nullable=True))
    op.add_column('characters', sa.Column('wisdom', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('constitution', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('silver', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('copper', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('dexterity', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('electrum', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('platinum', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('intelligence', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('img',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img', mysql.TEXT(), nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=False),
    sa.Column('mimetype', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('images')
    # ### end Alembic commands ###
