"""empty message

Revision ID: 47ebd263e92d
Revises: 45750fca9568
Create Date: 2021-09-12 20:23:02.923707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ebd263e92d'
down_revision = '45750fca9568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'realname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('realname', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
