"""empty message

Revision ID: 5021e414436d
Revises: 2ff1ed968a1f
Create Date: 2021-09-05 09:58:43.912767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5021e414436d'
down_revision = '2ff1ed968a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loot', 'copper_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loot', sa.Column('copper_value', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
