"""np_cs table name to npcs

Revision ID: 538564b92c04
Revises: 0999ba8704a6
Create Date: 2021-11-20 15:44:39.502976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '538564b92c04'
down_revision = '0999ba8704a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('np_cs', 'npcs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('npcs', 'np_cs')
    # ### end Alembic commands ###
