"""big changes

Revision ID: 5f9e841b7ab8
Revises: 83616baa15f1
Create Date: 2021-11-19 19:52:32.685755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9e841b7ab8'
down_revision = '83616baa15f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'users_id', new_column_name="user_id")
    op.alter_column('players', 'games_id', new_column_name="game_id")
    op.alter_column('sessions', 'games_id', new_column_name="game_id")
    op.alter_column('notes', 'user_id', new_column_name="origin_user_id")
    op.alter_column('notes', 'character', new_column_name="origin_character_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'user_id', new_column_name="users_id")
    op.alter_column('players', 'game_id', new_column_name="games_id")
    op.alter_column('sessions', 'game_id', new_column_name="games_id")
    op.alter_column('notes', 'origin_user_id', new_column_name="user_id")
    op.alter_column('notes', 'origin_character_id', new_column_name="character")
    # ### end Alembic commands ###
