"""empty message

Revision ID: 7597304b83a0
Revises: 7f7aea39c0b1
Create Date: 2021-07-26 09:02:15.528531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7597304b83a0'
down_revision = '7f7aea39c0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'published')
    # ### end Alembic commands ###
