"""empty message

Revision ID: 8acaafd40b1a
Revises: 4b358af1ac72
Create Date: 2021-09-05 10:06:07.398100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8acaafd40b1a'
down_revision = '4b358af1ac72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'imglink')
    op.drop_column('games', 'imglink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('imglink', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('characters', sa.Column('imglink', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
