"""empty message

Revision ID: b132f6ac86a4
Revises: c9da68d48a61
Create Date: 2021-09-24 17:40:54.390527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b132f6ac86a4'
down_revision = 'c9da68d48a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('to_gm', sa.Boolean(), nullable=True))
    op.drop_column('notes', 'in_character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('in_character', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('notes', 'to_gm')
    # ### end Alembic commands ###
