"""empty message

Revision ID: b86fc8f46a8d
Revises: 41024ba6cb8f
Create Date: 2021-08-01 16:30:07.580171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86fc8f46a8d'
down_revision = '41024ba6cb8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    # ### end Alembic commands ###
