"""empty message

Revision ID: c86671055c02
Revises: 1b9cd380b8c6
Create Date: 2021-09-09 15:11:55.356755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c86671055c02'
down_revision = '1b9cd380b8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('img', sa.Text(), nullable=True))
    op.add_column('test', sa.Column('binary', sa.LargeBinary(), nullable=True))
    op.drop_column('test', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('test', mysql.TEXT(), nullable=True))
    op.drop_column('test', 'binary')
    op.drop_column('test', 'img')
    # ### end Alembic commands ###
