"""empty message

Revision ID: d265ade8ad5a
Revises: 6ddfcf48e572
Create Date: 2021-07-14 09:55:12.306077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd265ade8ad5a'
down_revision = '6ddfcf48e572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('games_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['games_id'], ['games.id'], name='players_ibfk_1'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='players_ibfk_2'),
    sa.PrimaryKeyConstraint('users_id', 'games_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
