"""initial migrate after rename

Revision ID: f7f3d8a8158a
Revises: 
Create Date: 2021-09-30 14:09:35.735554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f3d8a8158a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hash", new_column_name = "hashed_password")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('np_cs')
    op.drop_table('notes')
    op.drop_table('loot')
    op.drop_table('sessions')
    op.drop_table('players')
    op.drop_table('places')
    op.drop_table('characters')
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('images')
    # ### end Alembic commands ###
