"""update places

Revision ID: 5e99945690fe
Revises: e091f1b683f4
Create Date: 2022-02-08 20:02:03.245357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e99945690fe'
down_revision = 'e091f1b683f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    op.drop_constraint('places_game_id_fkey', 'places', type_='foreignkey')
    op.drop_column('places', 'game_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('game_id', sa.INTEGER(), server_default=sa.text('-2'), autoincrement=False, nullable=False))
    op.create_foreign_key('places_game_id_fkey', 'places', 'games', ['game_id'], ['id'])
    op.drop_column('places', 'removed')
    # ### end Alembic commands ###
