"""update users

Revision ID: 7991280a5c74
Revises: 5e99945690fe
Create Date: 2022-02-08 20:04:46.794388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7991280a5c74'
down_revision = '5e99945690fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('removed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'removed')
    # ### end Alembic commands ###
