"""rename players

Revision ID: 7961f86915f5
Revises: 7991280a5c74
Create Date: 2022-02-08 20:05:24.010237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7961f86915f5'
down_revision = '7991280a5c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('players', 'bridgeusergames')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('bridgeusergames', 'players')
    # ### end Alembic commands ###
